#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjQuanLyLuongSanPham.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyLuongSanPham")]
	public partial class DataLuongSanPhamDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblAccount(tblAccount instance);
    partial void UpdatetblAccount(tblAccount instance);
    partial void DeletetblAccount(tblAccount instance);
    partial void InserttblSanPham(tblSanPham instance);
    partial void UpdatetblSanPham(tblSanPham instance);
    partial void DeletetblSanPham(tblSanPham instance);
    partial void InserttblCongDoan(tblCongDoan instance);
    partial void UpdatetblCongDoan(tblCongDoan instance);
    partial void DeletetblCongDoan(tblCongDoan instance);
    partial void InserttblChamCongCN(tblChamCongCN instance);
    partial void UpdatetblChamCongCN(tblChamCongCN instance);
    partial void DeletetblChamCongCN(tblChamCongCN instance);
    partial void InserttblChamCongNVHC(tblChamCongNVHC instance);
    partial void UpdatetblChamCongNVHC(tblChamCongNVHC instance);
    partial void DeletetblChamCongNVHC(tblChamCongNVHC instance);
    partial void InserttblChucVu(tblChucVu instance);
    partial void UpdatetblChucVu(tblChucVu instance);
    partial void DeletetblChucVu(tblChucVu instance);
    partial void InserttblHeSoLuong(tblHeSoLuong instance);
    partial void UpdatetblHeSoLuong(tblHeSoLuong instance);
    partial void DeletetblHeSoLuong(tblHeSoLuong instance);
    partial void InserttblHopDong(tblHopDong instance);
    partial void UpdatetblHopDong(tblHopDong instance);
    partial void DeletetblHopDong(tblHopDong instance);
    partial void InserttblLuongBHXH(tblLuongBHXH instance);
    partial void UpdatetblLuongBHXH(tblLuongBHXH instance);
    partial void DeletetblLuongBHXH(tblLuongBHXH instance);
    partial void InserttblLuongCN(tblLuongCN instance);
    partial void UpdatetblLuongCN(tblLuongCN instance);
    partial void DeletetblLuongCN(tblLuongCN instance);
    partial void InserttblLuongNVHC(tblLuongNVHC instance);
    partial void UpdatetblLuongNVHC(tblLuongNVHC instance);
    partial void DeletetblLuongNVHC(tblLuongNVHC instance);
    partial void InserttblNhanVien(tblNhanVien instance);
    partial void UpdatetblNhanVien(tblNhanVien instance);
    partial void DeletetblNhanVien(tblNhanVien instance);
    partial void InserttblQuyetDinhTangLuong(tblQuyetDinhTangLuong instance);
    partial void UpdatetblQuyetDinhTangLuong(tblQuyetDinhTangLuong instance);
    partial void DeletetblQuyetDinhTangLuong(tblQuyetDinhTangLuong instance);
    #endregion
		
		public DataLuongSanPhamDataContext() : 
				base(global::prjQuanLyLuongSanPham.Properties.Settings.Default.QuanLyLuongSanPhamConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public DataLuongSanPhamDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLuongSanPhamDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLuongSanPhamDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLuongSanPhamDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblAccount> tblAccounts
		{
			get
			{
				return this.GetTable<tblAccount>();
			}
		}
		
		public System.Data.Linq.Table<tblSanPham> tblSanPhams
		{
			get
			{
				return this.GetTable<tblSanPham>();
			}
		}
		
		public System.Data.Linq.Table<tblCongDoan> tblCongDoans
		{
			get
			{
				return this.GetTable<tblCongDoan>();
			}
		}
		
		public System.Data.Linq.Table<tblChamCongCN> tblChamCongCNs
		{
			get
			{
				return this.GetTable<tblChamCongCN>();
			}
		}
		
		public System.Data.Linq.Table<tblChamCongNVHC> tblChamCongNVHCs
		{
			get
			{
				return this.GetTable<tblChamCongNVHC>();
			}
		}
		
		public System.Data.Linq.Table<tblChucVu> tblChucVus
		{
			get
			{
				return this.GetTable<tblChucVu>();
			}
		}
		
		public System.Data.Linq.Table<tblHeSoLuong> tblHeSoLuongs
		{
			get
			{
				return this.GetTable<tblHeSoLuong>();
			}
		}
		
		public System.Data.Linq.Table<tblHopDong> tblHopDongs
		{
			get
			{
				return this.GetTable<tblHopDong>();
			}
		}
		
		public System.Data.Linq.Table<tblLuongBHXH> tblLuongBHXHs
		{
			get
			{
				return this.GetTable<tblLuongBHXH>();
			}
		}
		
		public System.Data.Linq.Table<tblLuongCN> tblLuongCNs
		{
			get
			{
				return this.GetTable<tblLuongCN>();
			}
		}
		
		public System.Data.Linq.Table<tblLuongNVHC> tblLuongNVHCs
		{
			get
			{
				return this.GetTable<tblLuongNVHC>();
			}
		}
		
		public System.Data.Linq.Table<tblNhanVien> tblNhanViens
		{
			get
			{
				return this.GetTable<tblNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<tblQuyetDinhTangLuong> tblQuyetDinhTangLuongs
		{
			get
			{
				return this.GetTable<tblQuyetDinhTangLuong>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAccount")]
	public partial class tblAccount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userName;
		
		private string _passWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnpassWordChanging(string value);
    partial void OnpassWordChanged();
    #endregion
		
		public tblAccount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passWord", DbType="NVarChar(50)")]
		public string passWord
		{
			get
			{
				return this._passWord;
			}
			set
			{
				if ((this._passWord != value))
				{
					this.OnpassWordChanging(value);
					this.SendPropertyChanging();
					this._passWord = value;
					this.SendPropertyChanged("passWord");
					this.OnpassWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSanPham")]
	public partial class tblSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maSP;
		
		private string _tenSanPham;
		
		private string _donViTinh;
		
		private System.Nullable<double> _donGia;
		
		private System.Nullable<int> _soLuong;
		
		private string _loaiSanPham;
		
		private string _maHD;
		
		private EntitySet<tblCongDoan> _tblCongDoans;
		
		private EntityRef<tblHopDong> _tblHopDong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSPChanging(string value);
    partial void OnmaSPChanged();
    partial void OntenSanPhamChanging(string value);
    partial void OntenSanPhamChanged();
    partial void OndonViTinhChanging(string value);
    partial void OndonViTinhChanged();
    partial void OndonGiaChanging(System.Nullable<double> value);
    partial void OndonGiaChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OnloaiSanPhamChanging(string value);
    partial void OnloaiSanPhamChanged();
    partial void OnmaHDChanging(string value);
    partial void OnmaHDChanged();
    #endregion
		
		public tblSanPham()
		{
			this._tblCongDoans = new EntitySet<tblCongDoan>(new Action<tblCongDoan>(this.attach_tblCongDoans), new Action<tblCongDoan>(this.detach_tblCongDoans));
			this._tblHopDong = default(EntityRef<tblHopDong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maSP
		{
			get
			{
				return this._maSP;
			}
			set
			{
				if ((this._maSP != value))
				{
					this.OnmaSPChanging(value);
					this.SendPropertyChanging();
					this._maSP = value;
					this.SendPropertyChanged("maSP");
					this.OnmaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenSanPham", DbType="NVarChar(50)")]
		public string tenSanPham
		{
			get
			{
				return this._tenSanPham;
			}
			set
			{
				if ((this._tenSanPham != value))
				{
					this.OntenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._tenSanPham = value;
					this.SendPropertyChanged("tenSanPham");
					this.OntenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donViTinh", DbType="NVarChar(50)")]
		public string donViTinh
		{
			get
			{
				return this._donViTinh;
			}
			set
			{
				if ((this._donViTinh != value))
				{
					this.OndonViTinhChanging(value);
					this.SendPropertyChanging();
					this._donViTinh = value;
					this.SendPropertyChanged("donViTinh");
					this.OndonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGia", DbType="Float")]
		public System.Nullable<double> donGia
		{
			get
			{
				return this._donGia;
			}
			set
			{
				if ((this._donGia != value))
				{
					this.OndonGiaChanging(value);
					this.SendPropertyChanging();
					this._donGia = value;
					this.SendPropertyChanged("donGia");
					this.OndonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiSanPham", DbType="NVarChar(50)")]
		public string loaiSanPham
		{
			get
			{
				return this._loaiSanPham;
			}
			set
			{
				if ((this._loaiSanPham != value))
				{
					this.OnloaiSanPhamChanging(value);
					this.SendPropertyChanging();
					this._loaiSanPham = value;
					this.SendPropertyChanged("loaiSanPham");
					this.OnloaiSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD", DbType="NVarChar(50)")]
		public string maHD
		{
			get
			{
				return this._maHD;
			}
			set
			{
				if ((this._maHD != value))
				{
					if (this._tblHopDong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHDChanging(value);
					this.SendPropertyChanging();
					this._maHD = value;
					this.SendPropertyChanged("maHD");
					this.OnmaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSanPham_tblCongDoan", Storage="_tblCongDoans", ThisKey="maSP", OtherKey="maSP")]
		public EntitySet<tblCongDoan> tblCongDoans
		{
			get
			{
				return this._tblCongDoans;
			}
			set
			{
				this._tblCongDoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHopDong_tblSanPham", Storage="_tblHopDong", ThisKey="maHD", OtherKey="maHD", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblHopDong tblHopDong
		{
			get
			{
				return this._tblHopDong.Entity;
			}
			set
			{
				tblHopDong previousValue = this._tblHopDong.Entity;
				if (((previousValue != value) 
							|| (this._tblHopDong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHopDong.Entity = null;
						previousValue.tblSanPhams.Remove(this);
					}
					this._tblHopDong.Entity = value;
					if ((value != null))
					{
						value.tblSanPhams.Add(this);
						this._maHD = value.maHD;
					}
					else
					{
						this._maHD = default(string);
					}
					this.SendPropertyChanged("tblHopDong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblCongDoans(tblCongDoan entity)
		{
			this.SendPropertyChanging();
			entity.tblSanPham = this;
		}
		
		private void detach_tblCongDoans(tblCongDoan entity)
		{
			this.SendPropertyChanging();
			entity.tblSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCongDoan")]
	public partial class tblCongDoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maCD;
		
		private string _tenCongDoan;
		
		private System.Nullable<int> _thuTuCongDoan;
		
		private System.Nullable<double> _donGia;
		
		private string _maSP;
		
		private System.Nullable<int> _soCongDoanCoTheLam;
		
		private EntitySet<tblChamCongCN> _tblChamCongCNs;
		
		private EntityRef<tblSanPham> _tblSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCDChanging(string value);
    partial void OnmaCDChanged();
    partial void OntenCongDoanChanging(string value);
    partial void OntenCongDoanChanged();
    partial void OnthuTuCongDoanChanging(System.Nullable<int> value);
    partial void OnthuTuCongDoanChanged();
    partial void OndonGiaChanging(System.Nullable<double> value);
    partial void OndonGiaChanged();
    partial void OnmaSPChanging(string value);
    partial void OnmaSPChanged();
    partial void OnsoCongDoanCoTheLamChanging(System.Nullable<int> value);
    partial void OnsoCongDoanCoTheLamChanged();
    #endregion
		
		public tblCongDoan()
		{
			this._tblChamCongCNs = new EntitySet<tblChamCongCN>(new Action<tblChamCongCN>(this.attach_tblChamCongCNs), new Action<tblChamCongCN>(this.detach_tblChamCongCNs));
			this._tblSanPham = default(EntityRef<tblSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCD", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maCD
		{
			get
			{
				return this._maCD;
			}
			set
			{
				if ((this._maCD != value))
				{
					this.OnmaCDChanging(value);
					this.SendPropertyChanging();
					this._maCD = value;
					this.SendPropertyChanged("maCD");
					this.OnmaCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCongDoan", DbType="NVarChar(50)")]
		public string tenCongDoan
		{
			get
			{
				return this._tenCongDoan;
			}
			set
			{
				if ((this._tenCongDoan != value))
				{
					this.OntenCongDoanChanging(value);
					this.SendPropertyChanging();
					this._tenCongDoan = value;
					this.SendPropertyChanged("tenCongDoan");
					this.OntenCongDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thuTuCongDoan", DbType="Int")]
		public System.Nullable<int> thuTuCongDoan
		{
			get
			{
				return this._thuTuCongDoan;
			}
			set
			{
				if ((this._thuTuCongDoan != value))
				{
					this.OnthuTuCongDoanChanging(value);
					this.SendPropertyChanging();
					this._thuTuCongDoan = value;
					this.SendPropertyChanged("thuTuCongDoan");
					this.OnthuTuCongDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGia", DbType="Float")]
		public System.Nullable<double> donGia
		{
			get
			{
				return this._donGia;
			}
			set
			{
				if ((this._donGia != value))
				{
					this.OndonGiaChanging(value);
					this.SendPropertyChanging();
					this._donGia = value;
					this.SendPropertyChanged("donGia");
					this.OndonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSP", DbType="NVarChar(50)")]
		public string maSP
		{
			get
			{
				return this._maSP;
			}
			set
			{
				if ((this._maSP != value))
				{
					if (this._tblSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSPChanging(value);
					this.SendPropertyChanging();
					this._maSP = value;
					this.SendPropertyChanged("maSP");
					this.OnmaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soCongDoanCoTheLam", DbType="Int")]
		public System.Nullable<int> soCongDoanCoTheLam
		{
			get
			{
				return this._soCongDoanCoTheLam;
			}
			set
			{
				if ((this._soCongDoanCoTheLam != value))
				{
					this.OnsoCongDoanCoTheLamChanging(value);
					this.SendPropertyChanging();
					this._soCongDoanCoTheLam = value;
					this.SendPropertyChanged("soCongDoanCoTheLam");
					this.OnsoCongDoanCoTheLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCongDoan_tblChamCongCN", Storage="_tblChamCongCNs", ThisKey="maCD", OtherKey="maCD")]
		public EntitySet<tblChamCongCN> tblChamCongCNs
		{
			get
			{
				return this._tblChamCongCNs;
			}
			set
			{
				this._tblChamCongCNs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSanPham_tblCongDoan", Storage="_tblSanPham", ThisKey="maSP", OtherKey="maSP", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblSanPham tblSanPham
		{
			get
			{
				return this._tblSanPham.Entity;
			}
			set
			{
				tblSanPham previousValue = this._tblSanPham.Entity;
				if (((previousValue != value) 
							|| (this._tblSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSanPham.Entity = null;
						previousValue.tblCongDoans.Remove(this);
					}
					this._tblSanPham.Entity = value;
					if ((value != null))
					{
						value.tblCongDoans.Add(this);
						this._maSP = value.maSP;
					}
					else
					{
						this._maSP = default(string);
					}
					this.SendPropertyChanged("tblSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChamCongCNs(tblChamCongCN entity)
		{
			this.SendPropertyChanging();
			entity.tblCongDoan = this;
		}
		
		private void detach_tblChamCongCNs(tblChamCongCN entity)
		{
			this.SendPropertyChanging();
			entity.tblCongDoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChamCongCN")]
	public partial class tblChamCongCN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maCong;
		
		private string _maNV;
		
		private string _ca;
		
		private System.Nullable<int> _thang;
		
		private System.Nullable<int> _soCongDoan;
		
		private System.Nullable<int> _soCongDoanThietHai;
		
		private string _maCD;
		
		private EntitySet<tblLuongCN> _tblLuongCNs;
		
		private EntityRef<tblCongDoan> _tblCongDoan;
		
		private EntityRef<tblNhanVien> _tblNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCongChanging(string value);
    partial void OnmaCongChanged();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OncaChanging(string value);
    partial void OncaChanged();
    partial void OnthangChanging(System.Nullable<int> value);
    partial void OnthangChanged();
    partial void OnsoCongDoanChanging(System.Nullable<int> value);
    partial void OnsoCongDoanChanged();
    partial void OnsoCongDoanThietHaiChanging(System.Nullable<int> value);
    partial void OnsoCongDoanThietHaiChanged();
    partial void OnmaCDChanging(string value);
    partial void OnmaCDChanged();
    #endregion
		
		public tblChamCongCN()
		{
			this._tblLuongCNs = new EntitySet<tblLuongCN>(new Action<tblLuongCN>(this.attach_tblLuongCNs), new Action<tblLuongCN>(this.detach_tblLuongCNs));
			this._tblCongDoan = default(EntityRef<tblCongDoan>);
			this._tblNhanVien = default(EntityRef<tblNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCong", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maCong
		{
			get
			{
				return this._maCong;
			}
			set
			{
				if ((this._maCong != value))
				{
					this.OnmaCongChanging(value);
					this.SendPropertyChanging();
					this._maCong = value;
					this.SendPropertyChanged("maCong");
					this.OnmaCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NVarChar(50)")]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._tblNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ca", DbType="NVarChar(50)")]
		public string ca
		{
			get
			{
				return this._ca;
			}
			set
			{
				if ((this._ca != value))
				{
					this.OncaChanging(value);
					this.SendPropertyChanging();
					this._ca = value;
					this.SendPropertyChanged("ca");
					this.OncaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thang", DbType="Int")]
		public System.Nullable<int> thang
		{
			get
			{
				return this._thang;
			}
			set
			{
				if ((this._thang != value))
				{
					this.OnthangChanging(value);
					this.SendPropertyChanging();
					this._thang = value;
					this.SendPropertyChanged("thang");
					this.OnthangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soCongDoan", DbType="Int")]
		public System.Nullable<int> soCongDoan
		{
			get
			{
				return this._soCongDoan;
			}
			set
			{
				if ((this._soCongDoan != value))
				{
					this.OnsoCongDoanChanging(value);
					this.SendPropertyChanging();
					this._soCongDoan = value;
					this.SendPropertyChanged("soCongDoan");
					this.OnsoCongDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soCongDoanThietHai", DbType="Int")]
		public System.Nullable<int> soCongDoanThietHai
		{
			get
			{
				return this._soCongDoanThietHai;
			}
			set
			{
				if ((this._soCongDoanThietHai != value))
				{
					this.OnsoCongDoanThietHaiChanging(value);
					this.SendPropertyChanging();
					this._soCongDoanThietHai = value;
					this.SendPropertyChanged("soCongDoanThietHai");
					this.OnsoCongDoanThietHaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCD", DbType="NVarChar(50)")]
		public string maCD
		{
			get
			{
				return this._maCD;
			}
			set
			{
				if ((this._maCD != value))
				{
					if (this._tblCongDoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaCDChanging(value);
					this.SendPropertyChanging();
					this._maCD = value;
					this.SendPropertyChanged("maCD");
					this.OnmaCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblChamCongCN_tblLuongCN", Storage="_tblLuongCNs", ThisKey="maCong", OtherKey="maCong")]
		public EntitySet<tblLuongCN> tblLuongCNs
		{
			get
			{
				return this._tblLuongCNs;
			}
			set
			{
				this._tblLuongCNs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCongDoan_tblChamCongCN", Storage="_tblCongDoan", ThisKey="maCD", OtherKey="maCD", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblCongDoan tblCongDoan
		{
			get
			{
				return this._tblCongDoan.Entity;
			}
			set
			{
				tblCongDoan previousValue = this._tblCongDoan.Entity;
				if (((previousValue != value) 
							|| (this._tblCongDoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCongDoan.Entity = null;
						previousValue.tblChamCongCNs.Remove(this);
					}
					this._tblCongDoan.Entity = value;
					if ((value != null))
					{
						value.tblChamCongCNs.Add(this);
						this._maCD = value.maCD;
					}
					else
					{
						this._maCD = default(string);
					}
					this.SendPropertyChanged("tblCongDoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblChamCongCN", Storage="_tblNhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true)]
		public tblNhanVien tblNhanVien
		{
			get
			{
				return this._tblNhanVien.Entity;
			}
			set
			{
				tblNhanVien previousValue = this._tblNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tblNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhanVien.Entity = null;
						previousValue.tblChamCongCNs.Remove(this);
					}
					this._tblNhanVien.Entity = value;
					if ((value != null))
					{
						value.tblChamCongCNs.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("tblNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblLuongCNs(tblLuongCN entity)
		{
			this.SendPropertyChanging();
			entity.tblChamCongCN = this;
		}
		
		private void detach_tblLuongCNs(tblLuongCN entity)
		{
			this.SendPropertyChanging();
			entity.tblChamCongCN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChamCongNVHC")]
	public partial class tblChamCongNVHC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maCong;
		
		private System.Nullable<int> _thang;
		
		private System.Nullable<int> _soNgayLamViecThucTe;
		
		private System.Nullable<int> _soNgayCongChuan;
		
		private System.Nullable<int> _soNgayCongVuotChuan;
		
		private string _maNV;
		
		private EntityRef<tblNhanVien> _tblNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCongChanging(string value);
    partial void OnmaCongChanged();
    partial void OnthangChanging(System.Nullable<int> value);
    partial void OnthangChanged();
    partial void OnsoNgayLamViecThucTeChanging(System.Nullable<int> value);
    partial void OnsoNgayLamViecThucTeChanged();
    partial void OnsoNgayCongChuanChanging(System.Nullable<int> value);
    partial void OnsoNgayCongChuanChanged();
    partial void OnsoNgayCongVuotChuanChanging(System.Nullable<int> value);
    partial void OnsoNgayCongVuotChuanChanged();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    #endregion
		
		public tblChamCongNVHC()
		{
			this._tblNhanVien = default(EntityRef<tblNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCong", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maCong
		{
			get
			{
				return this._maCong;
			}
			set
			{
				if ((this._maCong != value))
				{
					this.OnmaCongChanging(value);
					this.SendPropertyChanging();
					this._maCong = value;
					this.SendPropertyChanged("maCong");
					this.OnmaCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thang", DbType="Int")]
		public System.Nullable<int> thang
		{
			get
			{
				return this._thang;
			}
			set
			{
				if ((this._thang != value))
				{
					this.OnthangChanging(value);
					this.SendPropertyChanging();
					this._thang = value;
					this.SendPropertyChanged("thang");
					this.OnthangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soNgayLamViecThucTe", DbType="Int")]
		public System.Nullable<int> soNgayLamViecThucTe
		{
			get
			{
				return this._soNgayLamViecThucTe;
			}
			set
			{
				if ((this._soNgayLamViecThucTe != value))
				{
					this.OnsoNgayLamViecThucTeChanging(value);
					this.SendPropertyChanging();
					this._soNgayLamViecThucTe = value;
					this.SendPropertyChanged("soNgayLamViecThucTe");
					this.OnsoNgayLamViecThucTeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soNgayCongChuan", DbType="Int")]
		public System.Nullable<int> soNgayCongChuan
		{
			get
			{
				return this._soNgayCongChuan;
			}
			set
			{
				if ((this._soNgayCongChuan != value))
				{
					this.OnsoNgayCongChuanChanging(value);
					this.SendPropertyChanging();
					this._soNgayCongChuan = value;
					this.SendPropertyChanged("soNgayCongChuan");
					this.OnsoNgayCongChuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soNgayCongVuotChuan", DbType="Int")]
		public System.Nullable<int> soNgayCongVuotChuan
		{
			get
			{
				return this._soNgayCongVuotChuan;
			}
			set
			{
				if ((this._soNgayCongVuotChuan != value))
				{
					this.OnsoNgayCongVuotChuanChanging(value);
					this.SendPropertyChanging();
					this._soNgayCongVuotChuan = value;
					this.SendPropertyChanged("soNgayCongVuotChuan");
					this.OnsoNgayCongVuotChuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NVarChar(50)")]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._tblNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblChamCongNVHC", Storage="_tblNhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblNhanVien tblNhanVien
		{
			get
			{
				return this._tblNhanVien.Entity;
			}
			set
			{
				tblNhanVien previousValue = this._tblNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tblNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhanVien.Entity = null;
						previousValue.tblChamCongNVHCs.Remove(this);
					}
					this._tblNhanVien.Entity = value;
					if ((value != null))
					{
						value.tblChamCongNVHCs.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("tblNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChucVu")]
	public partial class tblChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maCV;
		
		private string _tenChucVu;
		
		private System.Nullable<double> _phuCap;
		
		private EntitySet<tblNhanVien> _tblNhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCVChanging(string value);
    partial void OnmaCVChanged();
    partial void OntenChucVuChanging(string value);
    partial void OntenChucVuChanged();
    partial void OnphuCapChanging(System.Nullable<double> value);
    partial void OnphuCapChanged();
    #endregion
		
		public tblChucVu()
		{
			this._tblNhanViens = new EntitySet<tblNhanVien>(new Action<tblNhanVien>(this.attach_tblNhanViens), new Action<tblNhanVien>(this.detach_tblNhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maCV
		{
			get
			{
				return this._maCV;
			}
			set
			{
				if ((this._maCV != value))
				{
					this.OnmaCVChanging(value);
					this.SendPropertyChanging();
					this._maCV = value;
					this.SendPropertyChanged("maCV");
					this.OnmaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenChucVu", DbType="NVarChar(50)")]
		public string tenChucVu
		{
			get
			{
				return this._tenChucVu;
			}
			set
			{
				if ((this._tenChucVu != value))
				{
					this.OntenChucVuChanging(value);
					this.SendPropertyChanging();
					this._tenChucVu = value;
					this.SendPropertyChanged("tenChucVu");
					this.OntenChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phuCap", DbType="Float")]
		public System.Nullable<double> phuCap
		{
			get
			{
				return this._phuCap;
			}
			set
			{
				if ((this._phuCap != value))
				{
					this.OnphuCapChanging(value);
					this.SendPropertyChanging();
					this._phuCap = value;
					this.SendPropertyChanged("phuCap");
					this.OnphuCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblChucVu_tblNhanVien", Storage="_tblNhanViens", ThisKey="maCV", OtherKey="maCV")]
		public EntitySet<tblNhanVien> tblNhanViens
		{
			get
			{
				return this._tblNhanViens;
			}
			set
			{
				this._tblNhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblNhanViens(tblNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tblChucVu = this;
		}
		
		private void detach_tblNhanViens(tblNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tblChucVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHeSoLuong")]
	public partial class tblHeSoLuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHSL;
		
		private System.Nullable<double> _heSoLuongCB;
		
		private System.Nullable<double> _heSoLuongChinh;
		
		private string _trinhDoHocVan;
		
		private string _ngoaiNgu;
		
		private System.Nullable<int> _thamNienCongTac;
		
		private System.Nullable<System.DateTime> _ngayBatDauThamGiaCongTac;
		
		private string _maNV;
		
		private EntityRef<tblNhanVien> _tblNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHSLChanging(string value);
    partial void OnmaHSLChanged();
    partial void OnheSoLuongCBChanging(System.Nullable<double> value);
    partial void OnheSoLuongCBChanged();
    partial void OnheSoLuongChinhChanging(System.Nullable<double> value);
    partial void OnheSoLuongChinhChanged();
    partial void OntrinhDoHocVanChanging(string value);
    partial void OntrinhDoHocVanChanged();
    partial void OnngoaiNguChanging(string value);
    partial void OnngoaiNguChanged();
    partial void OnthamNienCongTacChanging(System.Nullable<int> value);
    partial void OnthamNienCongTacChanged();
    partial void OnngayBatDauThamGiaCongTacChanging(System.Nullable<System.DateTime> value);
    partial void OnngayBatDauThamGiaCongTacChanged();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    #endregion
		
		public tblHeSoLuong()
		{
			this._tblNhanVien = default(EntityRef<tblNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHSL", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHSL
		{
			get
			{
				return this._maHSL;
			}
			set
			{
				if ((this._maHSL != value))
				{
					this.OnmaHSLChanging(value);
					this.SendPropertyChanging();
					this._maHSL = value;
					this.SendPropertyChanged("maHSL");
					this.OnmaHSLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heSoLuongCB", DbType="Float")]
		public System.Nullable<double> heSoLuongCB
		{
			get
			{
				return this._heSoLuongCB;
			}
			set
			{
				if ((this._heSoLuongCB != value))
				{
					this.OnheSoLuongCBChanging(value);
					this.SendPropertyChanging();
					this._heSoLuongCB = value;
					this.SendPropertyChanged("heSoLuongCB");
					this.OnheSoLuongCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heSoLuongChinh", DbType="Float")]
		public System.Nullable<double> heSoLuongChinh
		{
			get
			{
				return this._heSoLuongChinh;
			}
			set
			{
				if ((this._heSoLuongChinh != value))
				{
					this.OnheSoLuongChinhChanging(value);
					this.SendPropertyChanging();
					this._heSoLuongChinh = value;
					this.SendPropertyChanged("heSoLuongChinh");
					this.OnheSoLuongChinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trinhDoHocVan", DbType="NVarChar(50)")]
		public string trinhDoHocVan
		{
			get
			{
				return this._trinhDoHocVan;
			}
			set
			{
				if ((this._trinhDoHocVan != value))
				{
					this.OntrinhDoHocVanChanging(value);
					this.SendPropertyChanging();
					this._trinhDoHocVan = value;
					this.SendPropertyChanged("trinhDoHocVan");
					this.OntrinhDoHocVanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngoaiNgu", DbType="NVarChar(50)")]
		public string ngoaiNgu
		{
			get
			{
				return this._ngoaiNgu;
			}
			set
			{
				if ((this._ngoaiNgu != value))
				{
					this.OnngoaiNguChanging(value);
					this.SendPropertyChanging();
					this._ngoaiNgu = value;
					this.SendPropertyChanged("ngoaiNgu");
					this.OnngoaiNguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thamNienCongTac", DbType="Int")]
		public System.Nullable<int> thamNienCongTac
		{
			get
			{
				return this._thamNienCongTac;
			}
			set
			{
				if ((this._thamNienCongTac != value))
				{
					this.OnthamNienCongTacChanging(value);
					this.SendPropertyChanging();
					this._thamNienCongTac = value;
					this.SendPropertyChanged("thamNienCongTac");
					this.OnthamNienCongTacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayBatDauThamGiaCongTac", DbType="Date")]
		public System.Nullable<System.DateTime> ngayBatDauThamGiaCongTac
		{
			get
			{
				return this._ngayBatDauThamGiaCongTac;
			}
			set
			{
				if ((this._ngayBatDauThamGiaCongTac != value))
				{
					this.OnngayBatDauThamGiaCongTacChanging(value);
					this.SendPropertyChanging();
					this._ngayBatDauThamGiaCongTac = value;
					this.SendPropertyChanged("ngayBatDauThamGiaCongTac");
					this.OnngayBatDauThamGiaCongTacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NVarChar(50)")]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._tblNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblHeSoLuong", Storage="_tblNhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblNhanVien tblNhanVien
		{
			get
			{
				return this._tblNhanVien.Entity;
			}
			set
			{
				tblNhanVien previousValue = this._tblNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tblNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhanVien.Entity = null;
						previousValue.tblHeSoLuongs.Remove(this);
					}
					this._tblNhanVien.Entity = value;
					if ((value != null))
					{
						value.tblHeSoLuongs.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("tblNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHopDong")]
	public partial class tblHopDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHD;
		
		private System.Nullable<int> _soThuTu;
		
		private string _tenHopDong;
		
		private System.Nullable<System.DateTime> _ngayBatDau;
		
		private System.Nullable<System.DateTime> _ngayKetThuc;
		
		private EntitySet<tblSanPham> _tblSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDChanging(string value);
    partial void OnmaHDChanged();
    partial void OnsoThuTuChanging(System.Nullable<int> value);
    partial void OnsoThuTuChanged();
    partial void OntenHopDongChanging(string value);
    partial void OntenHopDongChanged();
    partial void OnngayBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnngayBatDauChanged();
    partial void OnngayKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnngayKetThucChanged();
    #endregion
		
		public tblHopDong()
		{
			this._tblSanPhams = new EntitySet<tblSanPham>(new Action<tblSanPham>(this.attach_tblSanPhams), new Action<tblSanPham>(this.detach_tblSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHD
		{
			get
			{
				return this._maHD;
			}
			set
			{
				if ((this._maHD != value))
				{
					this.OnmaHDChanging(value);
					this.SendPropertyChanging();
					this._maHD = value;
					this.SendPropertyChanged("maHD");
					this.OnmaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soThuTu", DbType="Int")]
		public System.Nullable<int> soThuTu
		{
			get
			{
				return this._soThuTu;
			}
			set
			{
				if ((this._soThuTu != value))
				{
					this.OnsoThuTuChanging(value);
					this.SendPropertyChanging();
					this._soThuTu = value;
					this.SendPropertyChanged("soThuTu");
					this.OnsoThuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenHopDong", DbType="NVarChar(50)")]
		public string tenHopDong
		{
			get
			{
				return this._tenHopDong;
			}
			set
			{
				if ((this._tenHopDong != value))
				{
					this.OntenHopDongChanging(value);
					this.SendPropertyChanging();
					this._tenHopDong = value;
					this.SendPropertyChanged("tenHopDong");
					this.OntenHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayBatDau", DbType="Date")]
		public System.Nullable<System.DateTime> ngayBatDau
		{
			get
			{
				return this._ngayBatDau;
			}
			set
			{
				if ((this._ngayBatDau != value))
				{
					this.OnngayBatDauChanging(value);
					this.SendPropertyChanging();
					this._ngayBatDau = value;
					this.SendPropertyChanged("ngayBatDau");
					this.OnngayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayKetThuc", DbType="Date")]
		public System.Nullable<System.DateTime> ngayKetThuc
		{
			get
			{
				return this._ngayKetThuc;
			}
			set
			{
				if ((this._ngayKetThuc != value))
				{
					this.OnngayKetThucChanging(value);
					this.SendPropertyChanging();
					this._ngayKetThuc = value;
					this.SendPropertyChanged("ngayKetThuc");
					this.OnngayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHopDong_tblSanPham", Storage="_tblSanPhams", ThisKey="maHD", OtherKey="maHD")]
		public EntitySet<tblSanPham> tblSanPhams
		{
			get
			{
				return this._tblSanPhams;
			}
			set
			{
				this._tblSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblHopDong = this;
		}
		
		private void detach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblHopDong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLuongBHXH")]
	public partial class tblLuongBHXH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maBHXH;
		
		private System.Nullable<int> _thang;
		
		private System.Nullable<int> _soNgayNghiCoPhep;
		
		private System.Nullable<int> _tongSoNgayNghi;
		
		private System.Nullable<double> _tienNopBHXH;
		
		private string _maNV;
		
		private EntityRef<tblNhanVien> _tblNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaBHXHChanging(string value);
    partial void OnmaBHXHChanged();
    partial void OnthangChanging(System.Nullable<int> value);
    partial void OnthangChanged();
    partial void OnsoNgayNghiCoPhepChanging(System.Nullable<int> value);
    partial void OnsoNgayNghiCoPhepChanged();
    partial void OntongSoNgayNghiChanging(System.Nullable<int> value);
    partial void OntongSoNgayNghiChanged();
    partial void OntienNopBHXHChanging(System.Nullable<double> value);
    partial void OntienNopBHXHChanged();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    #endregion
		
		public tblLuongBHXH()
		{
			this._tblNhanVien = default(EntityRef<tblNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maBHXH", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maBHXH
		{
			get
			{
				return this._maBHXH;
			}
			set
			{
				if ((this._maBHXH != value))
				{
					this.OnmaBHXHChanging(value);
					this.SendPropertyChanging();
					this._maBHXH = value;
					this.SendPropertyChanged("maBHXH");
					this.OnmaBHXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thang", DbType="Int")]
		public System.Nullable<int> thang
		{
			get
			{
				return this._thang;
			}
			set
			{
				if ((this._thang != value))
				{
					this.OnthangChanging(value);
					this.SendPropertyChanging();
					this._thang = value;
					this.SendPropertyChanged("thang");
					this.OnthangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soNgayNghiCoPhep", DbType="Int")]
		public System.Nullable<int> soNgayNghiCoPhep
		{
			get
			{
				return this._soNgayNghiCoPhep;
			}
			set
			{
				if ((this._soNgayNghiCoPhep != value))
				{
					this.OnsoNgayNghiCoPhepChanging(value);
					this.SendPropertyChanging();
					this._soNgayNghiCoPhep = value;
					this.SendPropertyChanged("soNgayNghiCoPhep");
					this.OnsoNgayNghiCoPhepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongSoNgayNghi", DbType="Int")]
		public System.Nullable<int> tongSoNgayNghi
		{
			get
			{
				return this._tongSoNgayNghi;
			}
			set
			{
				if ((this._tongSoNgayNghi != value))
				{
					this.OntongSoNgayNghiChanging(value);
					this.SendPropertyChanging();
					this._tongSoNgayNghi = value;
					this.SendPropertyChanged("tongSoNgayNghi");
					this.OntongSoNgayNghiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tienNopBHXH", DbType="Float")]
		public System.Nullable<double> tienNopBHXH
		{
			get
			{
				return this._tienNopBHXH;
			}
			set
			{
				if ((this._tienNopBHXH != value))
				{
					this.OntienNopBHXHChanging(value);
					this.SendPropertyChanging();
					this._tienNopBHXH = value;
					this.SendPropertyChanged("tienNopBHXH");
					this.OntienNopBHXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NVarChar(50)")]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._tblNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblLuongBHXH", Storage="_tblNhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblNhanVien tblNhanVien
		{
			get
			{
				return this._tblNhanVien.Entity;
			}
			set
			{
				tblNhanVien previousValue = this._tblNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tblNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhanVien.Entity = null;
						previousValue.tblLuongBHXHs.Remove(this);
					}
					this._tblNhanVien.Entity = value;
					if ((value != null))
					{
						value.tblLuongBHXHs.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("tblNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLuongCN")]
	public partial class tblLuongCN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLuongCN;
		
		private System.Nullable<double> _luongChinh;
		
		private System.Nullable<int> _soGioLamCa12;
		
		private System.Nullable<int> _soGioLamCa3;
		
		private string _maCong;
		
		private string _maNV;
		
		private EntityRef<tblChamCongCN> _tblChamCongCN;
		
		private EntityRef<tblNhanVien> _tblNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLuongCNChanging(string value);
    partial void OnmaLuongCNChanged();
    partial void OnluongChinhChanging(System.Nullable<double> value);
    partial void OnluongChinhChanged();
    partial void OnsoGioLamCa12Changing(System.Nullable<int> value);
    partial void OnsoGioLamCa12Changed();
    partial void OnsoGioLamCa3Changing(System.Nullable<int> value);
    partial void OnsoGioLamCa3Changed();
    partial void OnmaCongChanging(string value);
    partial void OnmaCongChanged();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    #endregion
		
		public tblLuongCN()
		{
			this._tblChamCongCN = default(EntityRef<tblChamCongCN>);
			this._tblNhanVien = default(EntityRef<tblNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLuongCN", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLuongCN
		{
			get
			{
				return this._maLuongCN;
			}
			set
			{
				if ((this._maLuongCN != value))
				{
					this.OnmaLuongCNChanging(value);
					this.SendPropertyChanging();
					this._maLuongCN = value;
					this.SendPropertyChanged("maLuongCN");
					this.OnmaLuongCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luongChinh", DbType="Float")]
		public System.Nullable<double> luongChinh
		{
			get
			{
				return this._luongChinh;
			}
			set
			{
				if ((this._luongChinh != value))
				{
					this.OnluongChinhChanging(value);
					this.SendPropertyChanging();
					this._luongChinh = value;
					this.SendPropertyChanged("luongChinh");
					this.OnluongChinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soGioLamCa12", DbType="Int")]
		public System.Nullable<int> soGioLamCa12
		{
			get
			{
				return this._soGioLamCa12;
			}
			set
			{
				if ((this._soGioLamCa12 != value))
				{
					this.OnsoGioLamCa12Changing(value);
					this.SendPropertyChanging();
					this._soGioLamCa12 = value;
					this.SendPropertyChanged("soGioLamCa12");
					this.OnsoGioLamCa12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soGioLamCa3", DbType="Int")]
		public System.Nullable<int> soGioLamCa3
		{
			get
			{
				return this._soGioLamCa3;
			}
			set
			{
				if ((this._soGioLamCa3 != value))
				{
					this.OnsoGioLamCa3Changing(value);
					this.SendPropertyChanging();
					this._soGioLamCa3 = value;
					this.SendPropertyChanged("soGioLamCa3");
					this.OnsoGioLamCa3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCong", DbType="NVarChar(50)")]
		public string maCong
		{
			get
			{
				return this._maCong;
			}
			set
			{
				if ((this._maCong != value))
				{
					if (this._tblChamCongCN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaCongChanging(value);
					this.SendPropertyChanging();
					this._maCong = value;
					this.SendPropertyChanged("maCong");
					this.OnmaCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NVarChar(50)")]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._tblNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblChamCongCN_tblLuongCN", Storage="_tblChamCongCN", ThisKey="maCong", OtherKey="maCong", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblChamCongCN tblChamCongCN
		{
			get
			{
				return this._tblChamCongCN.Entity;
			}
			set
			{
				tblChamCongCN previousValue = this._tblChamCongCN.Entity;
				if (((previousValue != value) 
							|| (this._tblChamCongCN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblChamCongCN.Entity = null;
						previousValue.tblLuongCNs.Remove(this);
					}
					this._tblChamCongCN.Entity = value;
					if ((value != null))
					{
						value.tblLuongCNs.Add(this);
						this._maCong = value.maCong;
					}
					else
					{
						this._maCong = default(string);
					}
					this.SendPropertyChanged("tblChamCongCN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblLuongCN", Storage="_tblNhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblNhanVien tblNhanVien
		{
			get
			{
				return this._tblNhanVien.Entity;
			}
			set
			{
				tblNhanVien previousValue = this._tblNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tblNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhanVien.Entity = null;
						previousValue.tblLuongCNs.Remove(this);
					}
					this._tblNhanVien.Entity = value;
					if ((value != null))
					{
						value.tblLuongCNs.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("tblNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLuongNVHC")]
	public partial class tblLuongNVHC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLuongNVHC;
		
		private System.Nullable<double> _luongCB;
		
		private System.Nullable<double> _luongTangCaMotNgay;
		
		private System.Nullable<double> _luongChinh;
		
		private string _maNV;
		
		private string _maCong;
		
		private string _maHSL;
		
		private string _maBHXH;
		
		private System.Nullable<double> _heSoTangCa;
		
		private EntityRef<tblNhanVien> _tblNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLuongNVHCChanging(string value);
    partial void OnmaLuongNVHCChanged();
    partial void OnluongCBChanging(System.Nullable<double> value);
    partial void OnluongCBChanged();
    partial void OnluongTangCaMotNgayChanging(System.Nullable<double> value);
    partial void OnluongTangCaMotNgayChanged();
    partial void OnluongChinhChanging(System.Nullable<double> value);
    partial void OnluongChinhChanged();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OnmaCongChanging(string value);
    partial void OnmaCongChanged();
    partial void OnmaHSLChanging(string value);
    partial void OnmaHSLChanged();
    partial void OnmaBHXHChanging(string value);
    partial void OnmaBHXHChanged();
    partial void OnheSoTangCaChanging(System.Nullable<double> value);
    partial void OnheSoTangCaChanged();
    #endregion
		
		public tblLuongNVHC()
		{
			this._tblNhanVien = default(EntityRef<tblNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLuongNVHC", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLuongNVHC
		{
			get
			{
				return this._maLuongNVHC;
			}
			set
			{
				if ((this._maLuongNVHC != value))
				{
					this.OnmaLuongNVHCChanging(value);
					this.SendPropertyChanging();
					this._maLuongNVHC = value;
					this.SendPropertyChanged("maLuongNVHC");
					this.OnmaLuongNVHCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luongCB", DbType="Float")]
		public System.Nullable<double> luongCB
		{
			get
			{
				return this._luongCB;
			}
			set
			{
				if ((this._luongCB != value))
				{
					this.OnluongCBChanging(value);
					this.SendPropertyChanging();
					this._luongCB = value;
					this.SendPropertyChanged("luongCB");
					this.OnluongCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luongTangCaMotNgay", DbType="Float")]
		public System.Nullable<double> luongTangCaMotNgay
		{
			get
			{
				return this._luongTangCaMotNgay;
			}
			set
			{
				if ((this._luongTangCaMotNgay != value))
				{
					this.OnluongTangCaMotNgayChanging(value);
					this.SendPropertyChanging();
					this._luongTangCaMotNgay = value;
					this.SendPropertyChanged("luongTangCaMotNgay");
					this.OnluongTangCaMotNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luongChinh", DbType="Float")]
		public System.Nullable<double> luongChinh
		{
			get
			{
				return this._luongChinh;
			}
			set
			{
				if ((this._luongChinh != value))
				{
					this.OnluongChinhChanging(value);
					this.SendPropertyChanging();
					this._luongChinh = value;
					this.SendPropertyChanged("luongChinh");
					this.OnluongChinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NVarChar(50)")]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._tblNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCong", DbType="NVarChar(50)")]
		public string maCong
		{
			get
			{
				return this._maCong;
			}
			set
			{
				if ((this._maCong != value))
				{
					this.OnmaCongChanging(value);
					this.SendPropertyChanging();
					this._maCong = value;
					this.SendPropertyChanged("maCong");
					this.OnmaCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHSL", DbType="NVarChar(50)")]
		public string maHSL
		{
			get
			{
				return this._maHSL;
			}
			set
			{
				if ((this._maHSL != value))
				{
					this.OnmaHSLChanging(value);
					this.SendPropertyChanging();
					this._maHSL = value;
					this.SendPropertyChanged("maHSL");
					this.OnmaHSLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maBHXH", DbType="NVarChar(50)")]
		public string maBHXH
		{
			get
			{
				return this._maBHXH;
			}
			set
			{
				if ((this._maBHXH != value))
				{
					this.OnmaBHXHChanging(value);
					this.SendPropertyChanging();
					this._maBHXH = value;
					this.SendPropertyChanged("maBHXH");
					this.OnmaBHXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heSoTangCa", DbType="Float")]
		public System.Nullable<double> heSoTangCa
		{
			get
			{
				return this._heSoTangCa;
			}
			set
			{
				if ((this._heSoTangCa != value))
				{
					this.OnheSoTangCaChanging(value);
					this.SendPropertyChanging();
					this._heSoTangCa = value;
					this.SendPropertyChanged("heSoTangCa");
					this.OnheSoTangCaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblLuongNVHC", Storage="_tblNhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblNhanVien tblNhanVien
		{
			get
			{
				return this._tblNhanVien.Entity;
			}
			set
			{
				tblNhanVien previousValue = this._tblNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tblNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhanVien.Entity = null;
						previousValue.tblLuongNVHCs.Remove(this);
					}
					this._tblNhanVien.Entity = value;
					if ((value != null))
					{
						value.tblLuongNVHCs.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("tblNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNhanVien")]
	public partial class tblNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNV;
		
		private string _hoTen;
		
		private string _gioiTinh;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _donViQuanLy;
		
		private string _soDienThoai;
		
		private string _email;
		
		private string _loaiNV;
		
		private string _maQDTL;
		
		private string _maCV;
		
		private EntitySet<tblChamCongCN> _tblChamCongCNs;
		
		private EntitySet<tblChamCongNVHC> _tblChamCongNVHCs;
		
		private EntitySet<tblHeSoLuong> _tblHeSoLuongs;
		
		private EntitySet<tblLuongBHXH> _tblLuongBHXHs;
		
		private EntitySet<tblLuongCN> _tblLuongCNs;
		
		private EntitySet<tblLuongNVHC> _tblLuongNVHCs;
		
		private EntityRef<tblChucVu> _tblChucVu;
		
		private EntityRef<tblQuyetDinhTangLuong> _tblQuyetDinhTangLuong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OnhoTenChanging(string value);
    partial void OnhoTenChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OndonViQuanLyChanging(string value);
    partial void OndonViQuanLyChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnloaiNVChanging(string value);
    partial void OnloaiNVChanged();
    partial void OnmaQDTLChanging(string value);
    partial void OnmaQDTLChanged();
    partial void OnmaCVChanging(string value);
    partial void OnmaCVChanged();
    #endregion
		
		public tblNhanVien()
		{
			this._tblChamCongCNs = new EntitySet<tblChamCongCN>(new Action<tblChamCongCN>(this.attach_tblChamCongCNs), new Action<tblChamCongCN>(this.detach_tblChamCongCNs));
			this._tblChamCongNVHCs = new EntitySet<tblChamCongNVHC>(new Action<tblChamCongNVHC>(this.attach_tblChamCongNVHCs), new Action<tblChamCongNVHC>(this.detach_tblChamCongNVHCs));
			this._tblHeSoLuongs = new EntitySet<tblHeSoLuong>(new Action<tblHeSoLuong>(this.attach_tblHeSoLuongs), new Action<tblHeSoLuong>(this.detach_tblHeSoLuongs));
			this._tblLuongBHXHs = new EntitySet<tblLuongBHXH>(new Action<tblLuongBHXH>(this.attach_tblLuongBHXHs), new Action<tblLuongBHXH>(this.detach_tblLuongBHXHs));
			this._tblLuongCNs = new EntitySet<tblLuongCN>(new Action<tblLuongCN>(this.attach_tblLuongCNs), new Action<tblLuongCN>(this.detach_tblLuongCNs));
			this._tblLuongNVHCs = new EntitySet<tblLuongNVHC>(new Action<tblLuongNVHC>(this.attach_tblLuongNVHCs), new Action<tblLuongNVHC>(this.detach_tblLuongNVHCs));
			this._tblChucVu = default(EntityRef<tblChucVu>);
			this._tblQuyetDinhTangLuong = default(EntityRef<tblQuyetDinhTangLuong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NVarChar(50)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this.OnhoTenChanging(value);
					this.SendPropertyChanging();
					this._hoTen = value;
					this.SendPropertyChanged("hoTen");
					this.OnhoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(50)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donViQuanLy", DbType="NVarChar(50)")]
		public string donViQuanLy
		{
			get
			{
				return this._donViQuanLy;
			}
			set
			{
				if ((this._donViQuanLy != value))
				{
					this.OndonViQuanLyChanging(value);
					this.SendPropertyChanging();
					this._donViQuanLy = value;
					this.SendPropertyChanged("donViQuanLy");
					this.OndonViQuanLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="NVarChar(50)")]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiNV", DbType="NVarChar(50)")]
		public string loaiNV
		{
			get
			{
				return this._loaiNV;
			}
			set
			{
				if ((this._loaiNV != value))
				{
					this.OnloaiNVChanging(value);
					this.SendPropertyChanging();
					this._loaiNV = value;
					this.SendPropertyChanged("loaiNV");
					this.OnloaiNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maQDTL", DbType="NVarChar(50)")]
		public string maQDTL
		{
			get
			{
				return this._maQDTL;
			}
			set
			{
				if ((this._maQDTL != value))
				{
					if (this._tblQuyetDinhTangLuong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaQDTLChanging(value);
					this.SendPropertyChanging();
					this._maQDTL = value;
					this.SendPropertyChanged("maQDTL");
					this.OnmaQDTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCV", DbType="NVarChar(50)")]
		public string maCV
		{
			get
			{
				return this._maCV;
			}
			set
			{
				if ((this._maCV != value))
				{
					if (this._tblChucVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaCVChanging(value);
					this.SendPropertyChanging();
					this._maCV = value;
					this.SendPropertyChanged("maCV");
					this.OnmaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblChamCongCN", Storage="_tblChamCongCNs", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<tblChamCongCN> tblChamCongCNs
		{
			get
			{
				return this._tblChamCongCNs;
			}
			set
			{
				this._tblChamCongCNs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblChamCongNVHC", Storage="_tblChamCongNVHCs", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<tblChamCongNVHC> tblChamCongNVHCs
		{
			get
			{
				return this._tblChamCongNVHCs;
			}
			set
			{
				this._tblChamCongNVHCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblHeSoLuong", Storage="_tblHeSoLuongs", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<tblHeSoLuong> tblHeSoLuongs
		{
			get
			{
				return this._tblHeSoLuongs;
			}
			set
			{
				this._tblHeSoLuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblLuongBHXH", Storage="_tblLuongBHXHs", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<tblLuongBHXH> tblLuongBHXHs
		{
			get
			{
				return this._tblLuongBHXHs;
			}
			set
			{
				this._tblLuongBHXHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblLuongCN", Storage="_tblLuongCNs", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<tblLuongCN> tblLuongCNs
		{
			get
			{
				return this._tblLuongCNs;
			}
			set
			{
				this._tblLuongCNs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblLuongNVHC", Storage="_tblLuongNVHCs", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<tblLuongNVHC> tblLuongNVHCs
		{
			get
			{
				return this._tblLuongNVHCs;
			}
			set
			{
				this._tblLuongNVHCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblChucVu_tblNhanVien", Storage="_tblChucVu", ThisKey="maCV", OtherKey="maCV", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblChucVu tblChucVu
		{
			get
			{
				return this._tblChucVu.Entity;
			}
			set
			{
				tblChucVu previousValue = this._tblChucVu.Entity;
				if (((previousValue != value) 
							|| (this._tblChucVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblChucVu.Entity = null;
						previousValue.tblNhanViens.Remove(this);
					}
					this._tblChucVu.Entity = value;
					if ((value != null))
					{
						value.tblNhanViens.Add(this);
						this._maCV = value.maCV;
					}
					else
					{
						this._maCV = default(string);
					}
					this.SendPropertyChanged("tblChucVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblQuyetDinhTangLuong_tblNhanVien", Storage="_tblQuyetDinhTangLuong", ThisKey="maQDTL", OtherKey="maQD", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblQuyetDinhTangLuong tblQuyetDinhTangLuong
		{
			get
			{
				return this._tblQuyetDinhTangLuong.Entity;
			}
			set
			{
				tblQuyetDinhTangLuong previousValue = this._tblQuyetDinhTangLuong.Entity;
				if (((previousValue != value) 
							|| (this._tblQuyetDinhTangLuong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblQuyetDinhTangLuong.Entity = null;
						previousValue.tblNhanViens.Remove(this);
					}
					this._tblQuyetDinhTangLuong.Entity = value;
					if ((value != null))
					{
						value.tblNhanViens.Add(this);
						this._maQDTL = value.maQD;
					}
					else
					{
						this._maQDTL = default(string);
					}
					this.SendPropertyChanged("tblQuyetDinhTangLuong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChamCongCNs(tblChamCongCN entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = this;
		}
		
		private void detach_tblChamCongCNs(tblChamCongCN entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = null;
		}
		
		private void attach_tblChamCongNVHCs(tblChamCongNVHC entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = this;
		}
		
		private void detach_tblChamCongNVHCs(tblChamCongNVHC entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = null;
		}
		
		private void attach_tblHeSoLuongs(tblHeSoLuong entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = this;
		}
		
		private void detach_tblHeSoLuongs(tblHeSoLuong entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = null;
		}
		
		private void attach_tblLuongBHXHs(tblLuongBHXH entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = this;
		}
		
		private void detach_tblLuongBHXHs(tblLuongBHXH entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = null;
		}
		
		private void attach_tblLuongCNs(tblLuongCN entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = this;
		}
		
		private void detach_tblLuongCNs(tblLuongCN entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = null;
		}
		
		private void attach_tblLuongNVHCs(tblLuongNVHC entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = this;
		}
		
		private void detach_tblLuongNVHCs(tblLuongNVHC entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblQuyetDinhTangLuong")]
	public partial class tblQuyetDinhTangLuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maQD;
		
		private System.Nullable<double> _luongTangTheoQuyetDinh;
		
		private string _noiDungQuyetDinh;
		
		private EntitySet<tblNhanVien> _tblNhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaQDChanging(string value);
    partial void OnmaQDChanged();
    partial void OnluongTangTheoQuyetDinhChanging(System.Nullable<double> value);
    partial void OnluongTangTheoQuyetDinhChanged();
    partial void OnnoiDungQuyetDinhChanging(string value);
    partial void OnnoiDungQuyetDinhChanged();
    #endregion
		
		public tblQuyetDinhTangLuong()
		{
			this._tblNhanViens = new EntitySet<tblNhanVien>(new Action<tblNhanVien>(this.attach_tblNhanViens), new Action<tblNhanVien>(this.detach_tblNhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maQD", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maQD
		{
			get
			{
				return this._maQD;
			}
			set
			{
				if ((this._maQD != value))
				{
					this.OnmaQDChanging(value);
					this.SendPropertyChanging();
					this._maQD = value;
					this.SendPropertyChanged("maQD");
					this.OnmaQDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luongTangTheoQuyetDinh", DbType="Float")]
		public System.Nullable<double> luongTangTheoQuyetDinh
		{
			get
			{
				return this._luongTangTheoQuyetDinh;
			}
			set
			{
				if ((this._luongTangTheoQuyetDinh != value))
				{
					this.OnluongTangTheoQuyetDinhChanging(value);
					this.SendPropertyChanging();
					this._luongTangTheoQuyetDinh = value;
					this.SendPropertyChanged("luongTangTheoQuyetDinh");
					this.OnluongTangTheoQuyetDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDungQuyetDinh", DbType="NVarChar(50)")]
		public string noiDungQuyetDinh
		{
			get
			{
				return this._noiDungQuyetDinh;
			}
			set
			{
				if ((this._noiDungQuyetDinh != value))
				{
					this.OnnoiDungQuyetDinhChanging(value);
					this.SendPropertyChanging();
					this._noiDungQuyetDinh = value;
					this.SendPropertyChanged("noiDungQuyetDinh");
					this.OnnoiDungQuyetDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblQuyetDinhTangLuong_tblNhanVien", Storage="_tblNhanViens", ThisKey="maQD", OtherKey="maQDTL")]
		public EntitySet<tblNhanVien> tblNhanViens
		{
			get
			{
				return this._tblNhanViens;
			}
			set
			{
				this._tblNhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblNhanViens(tblNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tblQuyetDinhTangLuong = this;
		}
		
		private void detach_tblNhanViens(tblNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tblQuyetDinhTangLuong = null;
		}
	}
}
#pragma warning restore 1591
